/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // ── Stitch M3 Color Tokens ───────────────────────────────────
        'on-error-container': '#93000a',
        'on-surface-variant': '#44474e',
        'inverse-on-surface': '#eef0ff',
        'surface': '#faf8ff',
        'outline-variant': '#c5c6cf',
        'surface-container-high': '#e2e7ff',
        'on-surface': '#131b2e',
        'outline': '#75777f',
        'primary-fixed-dim': '#b4c7ef',
        'secondary-container': '#92f5a4',
        'surface-container-highest': '#dae2fd',
        'on-secondary-fixed-variant': '#005323',
        'primary': '#000e27',
        'error': '#ba1a1a',
        'tertiary-container': '#3b1c00',
        'primary-container': '#0f2444',
        'inverse-surface': '#283044',
        'tertiary': '#1c0a00',
        'surface-container': '#eaedff',
        'surface-dim': '#d2d9f4',
        'on-primary-fixed': '#041b3b',
        'on-tertiary-fixed-variant': '#6e3900',
        'on-primary-fixed-variant': '#344769',
        'tertiary-fixed': '#ffdcc3',
        'secondary-fixed-dim': '#79db8d',
        'on-secondary-fixed': '#00210a',
        'tertiary-fixed-dim': '#ffb77d',
        'on-secondary': '#ffffff',
        'background': '#faf8ff',
        'on-primary': '#ffffff',
        'secondary-fixed': '#95f8a7',
        'on-tertiary-container': '#d27200',
        'on-background': '#131b2e',
        'on-primary-container': '#798cb1',
        'on-tertiary-fixed': '#2f1500',
        'surface-variant': '#dae2fd',
        'error-container': '#ffdad6',
        'surface-tint': '#4c5f82',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#faf8ff',
        'inverse-primary': '#b4c7ef',
        'primary-fixed': '#d7e3ff',
        'surface-container-low': '#f2f3ff',
        'secondary': '#006d30',
        'on-secondary-container': '#007233',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '0.75rem',
      },
      spacing: {
        'gutter-mobile': '1rem',
        'gutter-tablet': '1.5rem',
        'space-xs': '0.25rem',
        'space-md': '1rem',
        'container-max': '80rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'gutter-desktop': '2rem',
        'space-2xs': '0.125rem',
        'space-lg': '1.5rem',
        'space-sm': '0.5rem',
        'space-xl': '2rem',
      },
      maxWidth: {
        'container-max': '80rem',
      },
      fontFamily: {
        'public-sans': ['"Public Sans"', 'system-ui', 'sans-serif'],
        'noto-sans': ['"Noto Sans"', 'system-ui', 'sans-serif'],
        sans: ['"Noto Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'metric-display': ['36px', { lineHeight: '44px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
