import { Work } from './types';

export const MOCK_WORKS: Work[] = [
  {
    work_id: 'UP-RAM-001',
    work_code: 'UP-RAM-001',
    work_title: 'Rural Road Construction - Rampur-Bilari SH-42',
    work_description: 'Construction of 12.4 km rural road connecting Rampur to Bilari via State Highway 42. Includes drainage and culverts.',
    work_type: 'ROAD',
    constituency_name: 'Rampur (PC 15)',
    district_name: 'Rampur',
    state_name: 'Uttar Pradesh',
    state_code: 'UP',
    mp_id: 'UP-RAM-015',
    mp_name: 'Ghulam Mohammad',
    sanction_amount: 18500000,
    release_amount: 18500000,
    expenditure_amount: 18500000,
    sanction_date: '2023-04-15',
    completion_date: '2023-11-30',
    reported_lat: 28.8184,
    reported_lon: 79.0058,
    contractor_name: 'Bharat Infratech Pvt Ltd',
    contractor_gstin: '09AABCB1234C1Z5',
    implementing_agency: 'UP Rural Development Dept',
    scheme_year: 2023,
    status: 'COMPLETED',
    risk_score: 0.92,
    confidence_tier: 'L3_CRITICAL_CORROBORATED',
    active_signals: ['NDBI_NIL_CHANGE', 'FISCAL_VELOCITY', 'GSTIN_INVALIDATION'],
    has_satellite_audit: true,
  },
  {
    work_id: 'MH-NGP-004',
    work_code: 'MH-NGP-004',
    work_title: 'Community Health Sub-Centre Upgrade - Kamptee',
    work_description: 'Upgrade of existing PHC at Kamptee with OPD block, lab equipment, 10 beds, and biomedical waste facility.',
    work_type: 'HEALTH',
    constituency_name: 'Nagpur (PC 6)',
    district_name: 'Nagpur',
    state_name: 'Maharashtra',
    state_code: 'MH',
    mp_id: 'MH-NGP-006',
    mp_name: 'Nitin Gadkari',
    sanction_amount: 4200000,
    release_amount: 4200000,
    expenditure_amount: 1260000,
    sanction_date: '2024-01-10',
    reported_lat: 21.2144,
    reported_lon: 79.1875,
    contractor_name: 'Maharashtra Health Infra Ltd',
    contractor_gstin: '27AAHCM1234K1ZP',
    implementing_agency: 'CMHO Nagpur',
    scheme_year: 2024,
    status: 'IN_PROGRESS',
    risk_score: 0.71,
    confidence_tier: 'L2_HIGH_CONFIDENCE',
    active_signals: ['CONTRACTOR_NEXUS', 'ABNORMAL_FISCAL_VELOCITY'],
    has_satellite_audit: true,
  },
  {
    work_id: 'TG-HYD-013',
    work_code: 'TG-HYD-013',
    work_title: 'Solar Street Lighting — Shaikpet Ward 78',
    work_description: '120 solar-powered LED street lights installation at Shaikpet locality, Hyderabad West constituency.',
    work_type: 'ELECTRICITY',
    constituency_name: 'Hyderabad (PC 8)',
    district_name: 'Hyderabad',
    state_name: 'Telangana',
    state_code: 'TG',
    mp_id: 'TG-HYD-008',
    mp_name: 'Asaduddin Owaisi',
    sanction_amount: 1850000,
    release_amount: 1850000,
    expenditure_amount: 1850000,
    sanction_date: '2023-09-05',
    completion_date: '2024-01-25',
    reported_lat: 17.3985,
    reported_lon: 78.4323,
    contractor_name: 'SunTech Solar Solutions',
    contractor_gstin: '36AABCS5678L1ZA',
    implementing_agency: 'GHMC Ward 78',
    scheme_year: 2023,
    status: 'COMPLETED',
    risk_score: 0.23,
    confidence_tier: 'L1_PATTERNS',
    active_signals: ['CITIZEN_GROUND_CONTRADICTION'],
    has_satellite_audit: false,
  },
  {
    work_id: 'RJ-JOD-007',
    work_code: 'RJ-JOD-007',
    work_title: 'Anganwadi Centre Construction - Mandore Block',
    work_description: 'Construction of 3 Anganwadi centres in Mandore block including basic amenities and toilet facilities.',
    work_type: 'COMMUNITY_HALL',
    constituency_name: 'Jodhpur (PC 12)',
    district_name: 'Jodhpur',
    state_name: 'Rajasthan',
    state_code: 'RJ',
    mp_id: 'RJ-JOD-012',
    mp_name: 'Gajendra Singh Shekhawat',
    sanction_amount: 2750000,
    release_amount: 2750000,
    expenditure_amount: 2340000,
    sanction_date: '2023-07-20',
    reported_lat: 26.3521,
    reported_lon: 73.0294,
    contractor_name: 'Rajputana Constructions',
    contractor_gstin: '08AABCR8765M1ZQ',
    implementing_agency: 'Rajasthan WCD Department',
    scheme_year: 2023,
    status: 'IN_PROGRESS',
    risk_score: 0.44,
    confidence_tier: 'L1_PATTERNS',
    active_signals: ['WEATHER_IMPOSSIBILITY'],
    has_satellite_audit: true,
  },
  {
    work_id: 'KA-BLR-022',
    work_code: 'KA-BLR-022',
    work_title: 'Drinking Water Supply - Yelahanka Taluk',
    work_description: 'Underground pipeline installation for potable water supply to 5 villages in Yelahanka taluk.',
    work_type: 'WATER',
    constituency_name: 'Bangalore North (PC 24)',
    district_name: 'Bengaluru Urban',
    state_name: 'Karnataka',
    state_code: 'KA',
    mp_id: 'KA-BLR-024',
    mp_name: 'PC Mohan',
    sanction_amount: 7800000,
    release_amount: 7800000,
    expenditure_amount: 7800000,
    sanction_date: '2022-06-01',
    completion_date: '2023-03-28',
    reported_lat: 13.1007,
    reported_lon: 77.5949,
    contractor_name: 'Cauvery Infrastructure Ltd',
    contractor_gstin: '29AABCC9012N1ZM',
    implementing_agency: 'BWSSB Yelahanka Division',
    scheme_year: 2022,
    status: 'COMPLETED',
    risk_score: 0.12,
    confidence_tier: 'L1_PATTERNS',
    active_signals: [],
    has_satellite_audit: false,
  },
  {
    work_id: 'WB-KOL-031',
    work_code: 'WB-KOL-031',
    work_title: 'School Infrastructure - Jheel Meel Campus Renovation',
    work_description: 'Renovation of 8 classrooms, construction of science lab and digital library at Jheel Meel Government School.',
    work_type: 'SCHOOL',
    constituency_name: 'Jadavpur (PC 23)',
    district_name: 'Kolkata',
    state_name: 'West Bengal',
    state_code: 'WB',
    mp_id: 'WB-KOL-023',
    mp_name: 'Mimi Chakraborty',
    sanction_amount: 5500000,
    release_amount: 5500000,
    expenditure_amount: 0,
    sanction_date: '2024-03-01',
    reported_lat: 22.4996,
    reported_lon: 88.3714,
    contractor_name: 'Bengal Construction Works',
    contractor_gstin: '19AABCB4567P1ZR',
    implementing_agency: 'WB School Education Dept',
    scheme_year: 2024,
    status: 'SANCTIONED',
    risk_score: 0.65,
    confidence_tier: 'L2_HIGH_CONFIDENCE',
    active_signals: ['CROSS_SCHEME_DUPLICATE', 'CONTRACTOR_NEXUS'],
    has_satellite_audit: false,
  },
];
